name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor

    steps:
      - name: Generate snake SVG and GIF
        uses: Platane/snk@
